# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 644)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1400, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("/* 垂直滚动条 */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(150, 150, 150, 20%);\n"
"    margin: 2px 0;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #a0a0a0;\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #808080;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background: #606060;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: transparent;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* 水平滚动条（与垂直对称设计） */\n"
"QScrollBar:horizontal {\n"
"    height: 12px;\n"
"    background: rgba(150, 150, 150, 20%);\n"
"    margin: 0 2px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #a0a0a0;\n"
"    border-radius: 6px;\n"
"    min-width: 30px;  /* 水平滑块最小宽度 */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #808080;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background: #606060;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: transparent;\n"
"    width: 0px;  /* 隐藏左右箭头 */\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 841, 454))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_input.sizePolicy().hasHeightForWidth())
        self.user_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.user_input.setFont(font)
        self.user_input.setToolTip("")
        self.user_input.setStatusTip("")
        self.user_input.setWhatsThis("")
        self.user_input.setStyleSheet("QTextEdit, QPlainTextEdit {\n"
"    /* 原有文本框样式 */\n"
"    background-color: #f0f0f0;\n"
"    border-radius: 10px; \n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    padding: 10px;\n"
"\n"
"    /* 字体/文本样式（可选） */\n"
"    font-family: \"Microsoft YaHei\", Arial;\n"
"    font-size: 12pt;\n"
"\n"
"}\n"
"\n"
"/* 垂直滚动条样式 */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(240, 240, 240, 30%);\n"
"    margin: 2px 0;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #a0a0a0;\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #808080;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background: #606060;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: transparent;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.user_input.setPlainText("")
        self.user_input.setObjectName("user_input")
        self.horizontalLayout.addWidget(self.user_input)
        self.sent_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sent_btn.sizePolicy().hasHeightForWidth())
        self.sent_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sent_btn.setFont(font)
        self.sent_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sent_btn.setStyleSheet("QPushButton {\n"
"    /* 基础样式 - 使用您指定的颜色 */\n"
"    background-color: #66929ff5;  /* 主背景色 */\n"
"    border: 2px solid #5a82d5;   /* 稍深的边框色 */\n"
"    border-radius: 15px;\n"
"    color: #ffffff;              /* 白色文字 */\n"
"    font-size: 18px;\n"
"    font-weight: medium;\n"
"    padding: 8px 20px;\n"
"    min-width: 60px;\n"
"    \n"
"    /* 渐变效果 - 基于您颜色的变体 */\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #769ff5, stop:1 #66929ff5\n"
"    );\n"
"    \n"
"    /* 文字效果 */\n"
"    text-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);\n"
"}\n"
"\n"
"/* 悬停效果 - 稍微变亮 */\n"
"QPushButton:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #86afff, stop:1 #76a2ff\n"
"    );\n"
"    border-color: #6a92e5;\n"
"}\n"
"\n"
"/* 按下效果 - 加深颜色 */\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #5682e5, stop:1 #4672d5\n"
"    );\n"
"    padding: 9px 19px 7px 21px;\n"
"    border-color: #4a72c5;\n"
"}\n"
"\n"
"/* 禁用状态 - 灰色调 */\n"
"QPushButton:disabled {\n"
"    background: #c0c8d0;\n"
"    border-color: #b0b8c0;\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"/* 焦点状态 - 发光效果 */\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    border: 2px solid #a0c0ff;\n"
"    box-shadow: 0 0 5px rgba(160, 192, 255, 0.7);\n"
"}")
        self.sent_btn.setFlat(False)
        self.sent_btn.setObjectName("sent_btn")
        self.horizontalLayout.addWidget(self.sent_btn)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_tokens = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_tokens.setFont(font)
        self.label_tokens.setObjectName("label_tokens")
        self.horizontalLayout_2.addWidget(self.label_tokens)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_model = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_model.setFont(font)
        self.label_model.setObjectName("label_model")
        self.horizontalLayout_2.addWidget(self.label_model)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_role = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_role.setFont(font)
        self.label_role.setObjectName("label_role")
        self.horizontalLayout_2.addWidget(self.label_role)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.input_length = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.input_length.setFont(font)
        self.input_length.setObjectName("input_length")
        self.horizontalLayout_2.addWidget(self.input_length)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius: 20px; \n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(200, 200, 200);\n"
"color: rgb(120, 120, 120);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2.setStretch(7, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_4 = QtWidgets.QMenu(self.menu)
        self.menu_4.setObjectName("menu_4")
        self.menu_11 = QtWidgets.QMenu(self.menu)
        self.menu_11.setObjectName("menu_11")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_12 = QtWidgets.QMenu(self.menu_3)
        self.menu_12.setObjectName("menu_12")
        self.menu_14 = QtWidgets.QMenu(self.menu_3)
        self.menu_14.setObjectName("menu_14")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_15 = QtWidgets.QMenu(self.menubar)
        self.menu_15.setObjectName("menu_15")
        self.menu_notes = QtWidgets.QMenu(self.menu_15)
        self.menu_notes.setObjectName("menu_notes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_2 = QtWidgets.QAction(MainWindow)
        self.new_2.setObjectName("new_2")
        self.open_2 = QtWidgets.QAction(MainWindow)
        self.open_2.setObjectName("open_2")
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionupdate = QtWidgets.QAction(MainWindow)
        self.actionupdate.setObjectName("actionupdate")
        self.actionstart = QtWidgets.QAction(MainWindow)
        self.actionstart.setObjectName("actionstart")
        self.actionasd_2 = QtWidgets.QAction(MainWindow)
        self.actionasd_2.setObjectName("actionasd_2")
        self.actionda = QtWidgets.QAction(MainWindow)
        self.actionda.setObjectName("actionda")
        self.action_md = QtWidgets.QAction(MainWindow)
        self.action_md.setObjectName("action_md")
        self.action_html = QtWidgets.QAction(MainWindow)
        self.action_html.setObjectName("action_html")
        self.actionGPT = QtWidgets.QAction(MainWindow)
        self.actionGPT.setObjectName("actionGPT")
        self.actiontongyi = QtWidgets.QAction(MainWindow)
        self.actiontongyi.setObjectName("actiontongyi")
        self.actionwenxin = QtWidgets.QAction(MainWindow)
        self.actionwenxin.setObjectName("actionwenxin")
        self.actionxunfei = QtWidgets.QAction(MainWindow)
        self.actionxunfei.setObjectName("actionxunfei")
        self.actiongamma = QtWidgets.QAction(MainWindow)
        self.actiongamma.setObjectName("actiongamma")
        self.actionwpsAI = QtWidgets.QAction(MainWindow)
        self.actionwpsAI.setObjectName("actionwpsAI")
        self.actiontianyin = QtWidgets.QAction(MainWindow)
        self.actiontianyin.setObjectName("actiontianyin")
        self.actionlibulibu = QtWidgets.QAction(MainWindow)
        self.actionlibulibu.setObjectName("actionlibulibu")
        self.actionbaiduwendang = QtWidgets.QAction(MainWindow)
        self.actionbaiduwendang.setObjectName("actionbaiduwendang")
        self.actionai_bot = QtWidgets.QAction(MainWindow)
        self.actionai_bot.setObjectName("actionai_bot")
        self.actionmidjourney = QtWidgets.QAction(MainWindow)
        self.actionmidjourney.setObjectName("actionmidjourney")
        self.actionBing_DALLE3 = QtWidgets.QAction(MainWindow)
        self.actionBing_DALLE3.setObjectName("actionBing_DALLE3")
        self.actionaliyun = QtWidgets.QAction(MainWindow)
        self.actionaliyun.setObjectName("actionaliyun")
        self.actiongettokens = QtWidgets.QAction(MainWindow)
        self.actiongettokens.setObjectName("actiongettokens")
        self.actiondonation = QtWidgets.QAction(MainWindow)
        self.actiondonation.setObjectName("actiondonation")
        self.actioncancelstartup = QtWidgets.QAction(MainWindow)
        self.actioncancelstartup.setObjectName("actioncancelstartup")
        self.actionconfig = QtWidgets.QAction(MainWindow)
        self.actionconfig.setObjectName("actionconfig")
        self.actionzhushou = QtWidgets.QAction(MainWindow)
        self.actionzhushou.setObjectName("actionzhushou")
        self.actionzhongyiying = QtWidgets.QAction(MainWindow)
        self.actionzhongyiying.setObjectName("actionzhongyiying")
        self.actionyingyizhong = QtWidgets.QAction(MainWindow)
        self.actionyingyizhong.setObjectName("actionyingyizhong")
        self.actionlunwenrunse = QtWidgets.QAction(MainWindow)
        self.actionlunwenrunse.setObjectName("actionlunwenrunse")
        self.actionnvninvyou = QtWidgets.QAction(MainWindow)
        self.actionnvninvyou.setObjectName("actionnvninvyou")
        self.actionxuninanyou = QtWidgets.QAction(MainWindow)
        self.actionxuninanyou.setObjectName("actionxuninanyou")
        self.actionpython = QtWidgets.QAction(MainWindow)
        self.actionpython.setObjectName("actionpython")
        self.actionjava = QtWidgets.QAction(MainWindow)
        self.actionjava.setObjectName("actionjava")
        self.actionwebqianduan = QtWidgets.QAction(MainWindow)
        self.actionwebqianduan.setObjectName("actionwebqianduan")
        self.actionusername = QtWidgets.QAction(MainWindow)
        self.actionusername.setObjectName("actionusername")
        self.actionzhanan = QtWidgets.QAction(MainWindow)
        self.actionzhanan.setObjectName("actionzhanan")
        self.actiondeeplearning = QtWidgets.QAction(MainWindow)
        self.actiondeeplearning.setObjectName("actiondeeplearning")
        self.actionhiden = QtWidgets.QAction(MainWindow)
        self.actionhiden.setObjectName("actionhiden")
        self.action_docx = QtWidgets.QAction(MainWindow)
        self.action_docx.setObjectName("action_docx")
        self.action_txt = QtWidgets.QAction(MainWindow)
        self.action_txt.setObjectName("action_txt")
        self.action_pdf = QtWidgets.QAction(MainWindow)
        self.action_pdf.setObjectName("action_pdf")
        self.actionAPIkey = QtWidgets.QAction(MainWindow)
        self.actionAPIkey.setObjectName("actionAPIkey")
        self.actiontongyiqianwen = QtWidgets.QAction(MainWindow)
        self.actiontongyiqianwen.setObjectName("actiontongyiqianwen")
        self.actionsuno = QtWidgets.QAction(MainWindow)
        self.actionsuno.setObjectName("actionsuno")
        self.actiontishijinglin = QtWidgets.QAction(MainWindow)
        self.actiontishijinglin.setObjectName("actiontishijinglin")
        self.actionChatGPT_SC = QtWidgets.QAction(MainWindow)
        self.actionChatGPT_SC.setObjectName("actionChatGPT_SC")
        self.actionc_zhuanjai = QtWidgets.QAction(MainWindow)
        self.actionc_zhuanjai.setObjectName("actionc_zhuanjai")
        self.actionwebhouduan = QtWidgets.QAction(MainWindow)
        self.actionwebhouduan.setObjectName("actionwebhouduan")
        self.actionlinux = QtWidgets.QAction(MainWindow)
        self.actionlinux.setObjectName("actionlinux")
        self.actionmachine = QtWidgets.QAction(MainWindow)
        self.actionmachine.setObjectName("actionmachine")
        self.actiongpt_3_5_turbo_1106 = QtWidgets.QAction(MainWindow)
        self.actiongpt_3_5_turbo_1106.setObjectName("actiongpt_3_5_turbo_1106")
        self.actiongpt_4o_mini = QtWidgets.QAction(MainWindow)
        self.actiongpt_4o_mini.setObjectName("actiongpt_4o_mini")
        self.actiongpt_4o = QtWidgets.QAction(MainWindow)
        self.actiongpt_4o.setObjectName("actiongpt_4o")
        self.actionspark_lite = QtWidgets.QAction(MainWindow)
        self.actionspark_lite.setObjectName("actionspark_lite")
        self.actionsettings = QtWidgets.QAction(MainWindow)
        self.actionsettings.setObjectName("actionsettings")
        self.actiontheme = QtWidgets.QAction(MainWindow)
        self.actiontheme.setObjectName("actiontheme")
        self.actionvideo_serve = QtWidgets.QAction(MainWindow)
        self.actionvideo_serve.setObjectName("actionvideo_serve")
        self.actionexport_folder = QtWidgets.QAction(MainWindow)
        self.actionexport_folder.setObjectName("actionexport_folder")
        self.actionclear_screen = QtWidgets.QAction(MainWindow)
        self.actionclear_screen.setObjectName("actionclear_screen")
        self.actionexit_app = QtWidgets.QAction(MainWindow)
        self.actionexit_app.setObjectName("actionexit_app")
        self.actionchongqi = QtWidgets.QAction(MainWindow)
        self.actionchongqi.setObjectName("actionchongqi")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.actionopen_address = QtWidgets.QAction(MainWindow)
        self.actionopen_address.setObjectName("actionopen_address")
        self.menu_4.addAction(self.action_md)
        self.menu_4.addAction(self.action_html)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_docx)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_txt)
        self.menu_4.addAction(self.action_pdf)
        self.menu_11.addAction(self.actionzhushou)
        self.menu_11.addSeparator()
        self.menu_11.addAction(self.actionzhongyiying)
        self.menu_11.addAction(self.actionyingyizhong)
        self.menu_11.addAction(self.actionlunwenrunse)
        self.menu_11.addSeparator()
        self.menu_11.addAction(self.actionnvninvyou)
        self.menu_11.addAction(self.actionxuninanyou)
        self.menu_11.addAction(self.actionzhanan)
        self.menu_11.addSeparator()
        self.menu_11.addAction(self.actionc_zhuanjai)
        self.menu_11.addAction(self.actionjava)
        self.menu_11.addAction(self.actionpython)
        self.menu_11.addAction(self.actionwebqianduan)
        self.menu_11.addAction(self.actionwebhouduan)
        self.menu_11.addAction(self.actionlinux)
        self.menu_11.addAction(self.actiondeeplearning)
        self.menu_11.addAction(self.actionmachine)
        self.menu_11.addSeparator()
        self.menu.addAction(self.new_2)
        self.menu.addAction(self.actionclear_screen)
        self.menu.addAction(self.menu_4.menuAction())
        self.menu.addAction(self.actionexport_folder)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_11.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.actiongettokens)
        self.menu.addSeparator()
        self.menu.addAction(self.actionchongqi)
        self.menu.addAction(self.actionexit_app)
        self.menu_2.addAction(self.actionhelp)
        self.menu_2.addAction(self.actionupdate)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actiondonation)
        self.menu_2.addAction(self.actionopen_address)
        self.menu_2.addSeparator()
        self.menu_12.addAction(self.actionusername)
        self.menu_3.addAction(self.menu_12.menuAction())
        self.menu_3.addAction(self.menu_14.menuAction())
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionstart)
        self.menu_3.addAction(self.actioncancelstartup)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionsettings)
        self.menu_3.addAction(self.actiontheme)
        self.menu_15.addAction(self.menu_notes.menuAction())
        self.menu_15.addAction(self.actionvideo_serve)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_15.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_input.setPlaceholderText(_translate("MainWindow", "在此输入消息..."))
        self.sent_btn.setText(_translate("MainWindow", "Send"))
        self.label_tokens.setText(_translate("MainWindow", "tokens:"))
        self.label_4.setText(_translate("MainWindow", "|"))
        self.label_model.setText(_translate("MainWindow", "Model:"))
        self.label.setText(_translate("MainWindow", "|"))
        self.label_role.setText(_translate("MainWindow", "Role:"))
        self.label_3.setText(_translate("MainWindow", "|"))
        self.input_length.setText(_translate("MainWindow", "0/4000"))
        self.label_2.setText(_translate("MainWindow", "Author: CFU-Version: 2.1-Date: 20250508"))
        self.menu.setTitle(_translate("MainWindow", "开始"))
        self.menu_4.setTitle(_translate("MainWindow", "导出对话内容"))
        self.menu_11.setTitle(_translate("MainWindow", "角色"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "选项"))
        self.menu_12.setTitle(_translate("MainWindow", "个性化"))
        self.menu_14.setTitle(_translate("MainWindow", "模型切换"))
        self.menu_5.setTitle(_translate("MainWindow", "效率"))
        self.menu_15.setTitle(_translate("MainWindow", "工具"))
        self.menu_notes.setTitle(_translate("MainWindow", "记事本"))
        self.new_2.setText(_translate("MainWindow", "新对话"))
        self.open_2.setText(_translate("MainWindow", "打开对话"))
        self.save.setText(_translate("MainWindow", "保存对话"))
        self.actionhelp.setText(_translate("MainWindow", "使用文档"))
        self.actionupdate.setText(_translate("MainWindow", "检查更新"))
        self.actionstart.setText(_translate("MainWindow", "设置开机自启"))
        self.actionasd_2.setText(_translate("MainWindow", "asd"))
        self.actionda.setText(_translate("MainWindow", "最大/最小化窗口"))
        self.action_md.setText(_translate("MainWindow", ".md"))
        self.action_html.setText(_translate("MainWindow", ".html"))
        self.actionGPT.setText(_translate("MainWindow", "GPT"))
        self.actiontongyi.setText(_translate("MainWindow", "tongyi"))
        self.actionwenxin.setText(_translate("MainWindow", "文心一言"))
        self.actionxunfei.setText(_translate("MainWindow", "讯飞星火"))
        self.actiongamma.setText(_translate("MainWindow", "gamma"))
        self.actionwpsAI.setText(_translate("MainWindow", "wpsAI"))
        self.actiontianyin.setText(_translate("MainWindow", "网易天音"))
        self.actionlibulibu.setText(_translate("MainWindow", "libulibu"))
        self.actionbaiduwendang.setText(_translate("MainWindow", "百度文档助手"))
        self.actionai_bot.setText(_translate("MainWindow", "ai-bot"))
        self.actionmidjourney.setText(_translate("MainWindow", "midjourney"))
        self.actionBing_DALLE3.setText(_translate("MainWindow", "Bing-DALLE3"))
        self.actionaliyun.setText(_translate("MainWindow", "阿里云服务"))
        self.actiongettokens.setText(_translate("MainWindow", "我的激活码"))
        self.actiondonation.setText(_translate("MainWindow", "赞助"))
        self.actioncancelstartup.setText(_translate("MainWindow", "取消开机自启"))
        self.actionconfig.setText(_translate("MainWindow", "config"))
        self.actionzhushou.setText(_translate("MainWindow", "AI问答助手"))
        self.actionzhongyiying.setText(_translate("MainWindow", "中译英"))
        self.actionyingyizhong.setText(_translate("MainWindow", "英译中"))
        self.actionlunwenrunse.setText(_translate("MainWindow", "论文润色"))
        self.actionnvninvyou.setText(_translate("MainWindow", "虚拟女友"))
        self.actionxuninanyou.setText(_translate("MainWindow", "虚拟男友"))
        self.actionpython.setText(_translate("MainWindow", "python高手"))
        self.actionjava.setText(_translate("MainWindow", "java高手"))
        self.actionwebqianduan.setText(_translate("MainWindow", "web前端高手"))
        self.actionusername.setText(_translate("MainWindow", "自定义昵称"))
        self.actionzhanan.setText(_translate("MainWindow", "渣男"))
        self.actiondeeplearning.setText(_translate("MainWindow", "深度学习专家"))
        self.actionhiden.setText(_translate("MainWindow", "隐藏"))
        self.action_docx.setText(_translate("MainWindow", ".docx"))
        self.action_txt.setText(_translate("MainWindow", ".txt"))
        self.action_pdf.setText(_translate("MainWindow", ".pdf"))
        self.actionAPIkey.setText(_translate("MainWindow", "API Key"))
        self.actiontongyiqianwen.setText(_translate("MainWindow", "通义千问"))
        self.actionsuno.setText(_translate("MainWindow", "suno"))
        self.actiontishijinglin.setText(_translate("MainWindow", "提示精灵"))
        self.actionChatGPT_SC.setText(_translate("MainWindow", "ChatGPT_SC"))
        self.actionc_zhuanjai.setText(_translate("MainWindow", "c++高手"))
        self.actionwebhouduan.setText(_translate("MainWindow", "web后端高手"))
        self.actionlinux.setText(_translate("MainWindow", "linux高手"))
        self.actionmachine.setText(_translate("MainWindow", "机器学习专家"))
        self.actiongpt_3_5_turbo_1106.setText(_translate("MainWindow", "gpt-3.5-turbo-1106"))
        self.actiongpt_4o_mini.setText(_translate("MainWindow", "gpt-4o-mini"))
        self.actiongpt_4o.setText(_translate("MainWindow", "gpt-4o"))
        self.actionspark_lite.setText(_translate("MainWindow", "spark-lite"))
        self.actionsettings.setText(_translate("MainWindow", "通用设置"))
        self.actiontheme.setText(_translate("MainWindow", "主题设置"))
        self.actionvideo_serve.setText(_translate("MainWindow", "本地视频服务"))
        self.actionexport_folder.setText(_translate("MainWindow", "打开导出目录"))
        self.actionclear_screen.setText(_translate("MainWindow", "清屏"))
        self.actionexit_app.setText(_translate("MainWindow", "退出"))
        self.actionchongqi.setText(_translate("MainWindow", "重启"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.actionopen_address.setText(_translate("MainWindow", "开源仓库"))
