# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoteViewer(object):
    def setupUi(self, NoteViewer):
        NoteViewer.setObjectName("NoteViewer")
        NoteViewer.resize(569, 572)
        self.centralwidget = QtWidgets.QWidget(NoteViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.notes_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.notes_textEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.notes_textEdit.setObjectName("notes_textEdit")
        self.verticalLayout.addWidget(self.notes_textEdit)
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_info.setFont(font)
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        NoteViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NoteViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 23))
        self.menubar.setObjectName("menubar")
        NoteViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NoteViewer)
        self.statusbar.setObjectName("statusbar")
        NoteViewer.setStatusBar(self.statusbar)

        self.retranslateUi(NoteViewer)
        QtCore.QMetaObject.connectSlotsByName(NoteViewer)

    def retranslateUi(self, NoteViewer):
        _translate = QtCore.QCoreApplication.translate
        NoteViewer.setWindowTitle(_translate("NoteViewer", "MainWindow"))
        self.label_info.setText(_translate("NoteViewer", "TextLabel"))
